<Project>
  <PropertyGroup>
    <RepoRoot>$([System.IO.Path]::GetFullPath($(MSBuildThisFileDirectory)))</RepoRoot>
  </PropertyGroup>
  <Import Project="$(RepoRoot).props/*Build.props" />

  <PropertyGroup>
    <PackageTags>$(PackageTags);version-tags;msbuild;nuget;package</PackageTags>
    <Version>1.1.0</Version>
  </PropertyGroup>
</Project>
