<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <VersionTags>debug</VersionTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AdHoc.Build.VersionTags" VersionOverride="$(Version)" PrivateAssets="all" />
  </ItemGroup>

  <Target Name="_BuildPackage" BeforeTargets="CollectPackageReferences">
    <Exec Condition="!Exists('$(PackageOutputPath)AdHoc.Build.VersionTags.$(Version).nupkg')"
          Command="dotnet clean &quot;$(MSBuildThisFileDirectory)../../src/AdHoc.Build.VersionTags/AdHoc.Build.VersionTags.csproj&quot; --configuration Release &amp; dotnet pack &quot;$(MSBuildThisFileDirectory)../../src/AdHoc.Build.VersionTags/AdHoc.Build.VersionTags.csproj&quot;" />
  </Target>
</Project>